jobs:
- job: 'cppWindows'  
  pool:
    vmImage: vs2017-win2016    
  displayName: 'C++ (Windows)'

  strategy:
    maxParallel: 2
    matrix:
      x64-Release:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
  
  steps:
  - checkout: self
    submodules: recursive
  - task: CMake@1
    displayName: 'CMake .. -G "Visual Studio 15 2017 Win64"'
    inputs:
      workingDirectory: 'build'
      cmakeArgs: '.. -G "Visual Studio 15 2017 Win64"'

  - task: MSBuild@1
    displayName: 'Build solution build/FishStore.sln'
    inputs:
      solution: 'build/FishStore.sln'
      msbuildArguments: '/m /p:Configuration=$(buildConfiguration) /p:Platform=$(buildPlatform)'

  - script: |
      ctest -j 1 --interactive-debug-mode 0 --output-on-failure -C $(buildConfiguration) -R .*_test
    workingDirectory: 'build'
    displayName: 'Run Ctest'

- job: 'cppLinux'
  pool:
    vmImage: ubuntu-16.04
  displayName: 'C++ (Linux)'
  
  steps:
  - checkout: self
    submodules: recursive
  - script: |
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt update
      sudo apt install -y g++-7 libaio-dev uuid-dev libtbb-dev
    displayName: 'Install depdendencies'
  
  - script: |
      export CXX='g++-7'
      mkdir -p build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
    displayName: 'CMake Release Profile'
  
  - script: 'make -j'
    displayName: 'Compile'
    workingDirectory: 'build'
 
  - script:  'ctest -j 1 --interactive-debug-mode 0 --output-on-failure -R .*_test'
    displayName: 'Run Tests'
    workingDirectory: 'build'
